# Generated by Django 6.0.2 on 2026-02-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchmember',
            name='email',
            field=models.EmailField(default='Unknown', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='researchmember',
            name='title',
            field=models.CharField(default='Unknown', max_length=150),
            preserve_default=False,
        ),
    ]
