# Generated by Django 6.0.2 on 2026-02-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_researchmember_email_researchmember_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchmember',
            name='seo_description',
            field=models.TextField(blank=True, max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='researchmember',
            name='seo_title',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='researchmember',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
