# Generated by Django 6.0.2 on 2026-02-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_researchmember_seo_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchmember',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
