# Generated by Django 6.0.2 on 2026-02-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_researchmember_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='researchmember',
            options={'verbose_name': 'Araştırma Üyesi', 'verbose_name_plural': 'Araştırma Üyeleri'},
        ),
        migrations.AddField(
            model_name='researchmember',
            name='resim',
            field=models.ImageField(blank=True, null=True, upload_to='uyeresimleri'),
        ),
    ]
