# Generated by Django 6.0.2 on 2026-02-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_researchmember_options_researchmember_resim'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchmember',
            name='anasayfa',
            field=models.BooleanField(default=False),
        ),
    ]
