# Generated by Django 6.0.2 on 2026-02-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_researchmember_anasayfa'),
    ]

    operations = [
        migrations.CreateModel(
            name='hakkimizda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('metin', models.CharField(blank=True, max_length=150, null=True)),
                ('resim', models.ImageField(blank=True, null=True, upload_to='arkaplan')),
            ],
            options={
                'verbose_name': 'Hakkımızda',
                'verbose_name_plural': 'Hakkımızda',
            },
        ),
    ]
