# Generated by Django 6.0.2 on 2026-02-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_hakkimizda'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchmember',
            name='unvan',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='researchmember',
            name='uzmanlikAlani',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
